const express = require("express");
const multer = require('multer');
const { loginUser } = require("../controller/userlogin");
const { createReport } = require("../controller/createreport");
const { getAllReports } = require("../controller/reportcontroller");
const { Barangays } = require("../controller/BarangayController");
const { deleteReport } = require("../controller/deletereports");
const { createEvent, deleteEvent, getAllEvents } = require('../controller/evenandprogramcontroller');
const { checkReportsBeforeViewMap } = require('../controller/checkReportsBeforeViewMap');
const { updateReportStatus } = require('../controller/updatestatus');
const { getLineChartData } = require('../controller/linechartcontroller');
const { getPieChartData } = require('../controller/piechartcontroller');
const {getUser} = require ('../controller/UserManagemnt');
const {createUser} = require('../controller/createuser');
const {updateUser} = require ('../controller/updateUse');
const {deleteUser} = require ('../controller/deleteUser');
const {getLogs} = require('../controller/activitylogs');
const createLogs = require("../controller/createactivitylogs");
const { deleteLog } = require('../controller/deletelog');
const {getArchivedReports} = require('../controller/Archivedreports');
const { retrieveReport } = require('../controller/retriever');
const router = express.Router();
router.get('/line-data', getLineChartData);
router.get('/pie-data', getPieChartData);
const storage = multer.memoryStorage(); 
const upload = multer({ storage: storage });

router.post('/retrieve/:id', retrieveReport);
router.get('/archived', getArchivedReports);
router.delete('/deleteLog/:id', deleteLog);
router.post('/createLog', createLogs);
router.get('/getLogs', getLogs);
router.delete('/deleteUser/:id', deleteUser);
router.put('/updateUser/:id', updateUser);
router.post('/createUser', createUser);
router.get('/getUser', getUser);
router.get('/view-map', checkReportsBeforeViewMap);
router.put('/updateReportStatus/:id', upload.single('file'), updateReportStatus);
router.post('/createEvent', createEvent);
router.delete('/deleteEvents/:id', deleteEvent);
router.get('/getAllEvents', getAllEvents);
router.delete('/deleteReport/:id', deleteReport);
router.get('/Barangays', Barangays);
router.post('/Createreport', upload.single('file'), createReport);
router.post('/login', loginUser);
router.get('/reports', getAllReports);

module.exports = router;
