const express = require("express");
const { upload } = require("../middleware/upload");
const { loginUser } = require("../controller/userlogin");
const {getNewReports}  = require("../controller/newreport");
const { verifyOTP } = require('../controller/authcontroller');
const { createReport } = require("../controller/createreport");
const { getAllReports } = require("../controller/reportcontroller");
const { Barangays } = require("../controller/BarangayController");
const { deleteReport } = require("../controller/deletereports");
const { createEvent, deleteEvent, getAllEvents } = require('../controller/evenandprogramcontroller');
const {updateEvent} = require ('../controller/updateEvent');
const { checkReportsBeforeViewMap } = require('../controller/checkReportsBeforeViewMap');
const { updateReportStatus } = require('../controller/updatestatus');
const { getLineChartData } = require('../controller/linechartcontroller');
const { getPieChartData } = require('../controller/piechartcontroller');
const {getUser} = require ('../controller/UserManagemnt');
const {createUser} = require('../controller/createuser');
const {updateUser} = require ('../controller/updateUse');
const {deleteUser} = require ('../controller/deleteUser');
const {getLogs} = require('../controller/activitylogs');
const { createLogs } = require("../controller/createactivitylogs");
const {getLast28DaysReports}= require ("../controller/report-28-days");
const {getResolvedReports}=require("../controller/resolvenumber");
const {getArchivedReports} = require('../controller/Archivedreports');
const { retrieveReport } = require('../controller/retriever');
const { deleteArchivedReport } = require('../controller/deletearchive');
const { downloadReport } = require("../controller/convertion");
const {getMobileUser} = require("../controller/MobileUser");
const {deleteMUser}= require("../controller/deleteMUser");
const {getEventViews}= require("../controller/event-view");
const {authMiddleware} = require("../middleware/authMiddleware");
const {updateMUser}= require ("../controller/updateMuser");
const {getOngoingReport}=require("../controller/ongoingcout");
const {resendOtp}=require("../controller/resend-OTP");
const {verifyOTP} =require ("../controller/verifyOTP);
const router = express.Router();

router.get ("/verify",verifyOTP );
router.post("/resend-otp", resendOtp ); 
router.put('/updateMUser:id', authMiddleware,updateMUser);
router.get ("/event-views", getEventViews);
router.get ("/resolved-reports", getResolvedReports);   
router.get("/getreport28days", getLast28DaysReports);
router.get("/getOngoingReport",getOngoingReport);
router.delete ("/deleteMUser/:id", authMiddleware,deleteMUser);
router.get ("/getMobileUser", getMobileUser);
router.get("/:id/download", downloadReport);
router.get('/line-data', getLineChartData);
router.get('/pie-data', getPieChartData);
router.get('/new-report', getNewReports);
router.post('/verify', verifyOTP);
router.delete('/delete/:id', authMiddleware,deleteArchivedReport);
router.post('/retrieve/:id', authMiddleware,retrieveReport);
router.get('/archived', getArchivedReports);
router.post('/createLog',authMiddleware, createLogs);
router.get('/getLogs', getLogs);
router.delete('/deleteUser/:id', authMiddleware,deleteUser);
router.put('/updateUser/:id',authMiddleware, updateUser);
router.post('/createUser', authMiddleware,createUser);
router.get('/getUser', getUser);
router.get('/view-map', checkReportsBeforeViewMap);
router.put('/updateReportStatus/:id',authMiddleware, upload.single('file'), updateReportStatus);
router.post('/createEvent', authMiddleware,createEvent);
router.put('/updateEvent/:id', authMiddleware,updateEvent);
router.delete('/deleteEvents/:id',authMiddleware, deleteEvent);
router.get('/getAllEvents', getAllEvents);
router.delete('/deleteReport/:id',authMiddleware, deleteReport);
router.get('/Barangays', Barangays);
router.post('/Createreport',authMiddleware, upload.single('file'), createReport);
router.post('/login', loginUser);
router.get('/reports', getAllReports);

module.exports = router;

